post_upgrade() {
  cd /opt/fusiondirectory
  ./update-fusiondirectory
}

post_install() {
  cd /opt/fusiondirectory
  ./update-fusiondirectory
  echo
  echo "--------------------------------------------------------------------------"
  echo "1. Enable mod_php5 in httpd.conf"
  echo "2. Include '/etc/httpd/conf/extra/httpd-fusiondirectory.conf' in httpd.conf"
  echo "3. Disable open_basedir in php.ini"
  echo "4. Configure required modules in php.ini"
  echo "--------------------------------------------------------------------------"
}
