#!/bin/bash

PUPPET_ARGS=
[ -f /etc/conf.d/puppet ] && . /etc/conf.d/puppet

. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -o %PPID /usr/bin/puppetd`
case "$1" in
  start)
    stat_busy "Starting Puppet"
    [ -z "$PID" ] && /usr/bin/puppetd ${PUPPET_ARGS}
    if [ $? -gt 0 ]; then
      stat_fail
    else
      PID=`pidof -o %PPID /usr/bin/puppetd`
      echo $PID > /var/run/puppet.pid
      add_daemon puppet
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping Puppet"
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon puppet
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0
